### ISSUE TITLE
Announcement: `main` to be set as the default branch

### ISSUE THREAD

**Issue by jacobweinstock** [tinkerbell/pbnj#82]
# Making `main` the default branch

~On the _th of June 2021~, As soon as we locate a person with the correct permissions we will be renaming the master branch in this repository to main and making main the default branch. When this occurs there will be potential for some disruption. Please read the following to understand and prepare for the change.

## Things you will need to do

After you rename a branch in a repository on GitHub, any collaborator with a local clone of the repository will need to update the clone.

From the local clone of the repository on a computer, run the following commands to update the name of the default branch.

```bash
$ git branch -m master main
$ git fetch origin
$ git branch -u origin/main main
$ git remote set-head origin -a
```

Optionally, run the following command to remove tracking references to the old branch name.

```bash
$ git remote prune origin
```

## Things that will be done on the GitHub side

The following are things that you won’t have to worry about. They are here for transparency. 

1. We will rename the default branch
2. We will merge a PR into main that will update all references to "master"

By default GitHub will automatically do the following when we change the default branch name:

- Re-target any open pull requests
- Update any draft releases based on the branch
- Move any branch protection rules that explicitly reference the old name
- Update the branch used to build GitHub Pages, if applicable
- Show a notice to repository contributors, maintainers, and admins on the repository homepage with instructions to update 
- local copies of the repository
- Show a notice to contributors who git push to the old branch
- Redirect web requests for the old branch name to the new branch name
- Return a "Moved Permanently" response in API requests for the old branch name

Refs:
https://github.com/github/renaming

https://docs.github.com/en/github/administering-a-repository/managing-branches-in-your-repository/renaming-a-branch

https://docs.github.com/en/github/administering-a-repository/managing-branches-in-your-repository/renaming-a-branch#updating-a-local-clone-after-a-branch-name-changes

**Comment by displague** [comment]
We missed the target date. Based on how safe this operation is (with all of the redirects GH puts in place) and the level of notification provided by this issue, I think we can safely 'just do it'.

**Comment by jacobweinstock** [comment]
The question is who has the permissions to do so? @displague do you? maybe @tstromberg?

**Comment by tstromberg** [comment]
<img width="1479" alt="image" src="https://user-images.githubusercontent.com/101424/130649164-1e67170d-9a42-4e36-8215-f75af86b42ce.png">
