### ISSUE TITLE
Remove bouk/monkey requirement from machine_test.go & bmc_test.go

### ISSUE THREAD

**Issue by tstromberg** [tinkerbell/pbnj#94]
monkey is currently used by:

* `server/grpcsvr/oob/machine/machine_test.go`
* `server/grpcsvr/oob/bmc/bmc_test.go`

Why should it be removed?

* It only works on x86/x86-64 platforms, which means I am unable to run tests or linters
* The license forbids it's use: https://github.com/bouk/monkey/blob/master/LICENSE.md
* Requiring monkey-patching for tests is the sign of code that is not designed to be tested

**Comment by SergeyHydra** [comment]
@tstromberg Hi! I'm new to golang, but i want to try resolve this issue. Can you assignee it to me?

**Comment by tstromberg** [comment]
@SergeyHydra - It's yours! But be warned, this particular item may be a challenge for someone new to the language. Let us know if there is anything we can do to help!

If it's helpful at all, I find that most of the time these sort of mockings are caused by API's that don't allow clients to be passed in. While I am not yet familiar with PBnJ internals, it is a common pattern for `main()` and/or tests to setup connections and pass them in via a Config struct, such as:

```
type Config struct {
  SomeClient *x.Client
  OtherClient *y.Client
}
```

And then in tests set it up using:

```
x := oob.New(&Config{SomeClient: mockX, OtherClient: mockY})
```

This approach definitely beats mock libraries, reflection, and global variables.
